begin;

revoke insert (
  product_id,
  customer_name,
  email,
  phone,
  event_date,
  quantity,
  message,
  submitter_timezone,
  submitter_utc_offset_minutes
)
on table public.customer_inquiries
from anon, authenticated;

drop policy if exists "Public can submit customer inquiries"
on public.customer_inquiries;

create table if not exists private.customer_inquiry_rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  identifier_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  constraint customer_inquiry_rate_limit_events_scope_allowed check (
    scope in ('ip', 'email')
  ),
  constraint customer_inquiry_rate_limit_events_identifier_hash_not_blank check (
    btrim(identifier_hash) <> ''
  ),
  constraint customer_inquiry_rate_limit_events_expiry_valid check (
    expires_at > created_at
  )
);

create table if not exists private.customer_inquiry_submission_fingerprints (
  fingerprint_hash text primary key,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  constraint customer_inquiry_submission_fingerprints_hash_not_blank check (
    btrim(fingerprint_hash) <> ''
  ),
  constraint customer_inquiry_submission_fingerprints_expiry_valid check (
    expires_at > created_at
  )
);

create index if not exists customer_inquiry_rate_limit_events_scope_identifier_created_at_idx
  on private.customer_inquiry_rate_limit_events (
    scope,
    identifier_hash,
    created_at desc
  );

create index if not exists customer_inquiry_rate_limit_events_expires_at_idx
  on private.customer_inquiry_rate_limit_events (expires_at);

create index if not exists customer_inquiry_submission_fingerprints_expires_at_idx
  on private.customer_inquiry_submission_fingerprints (expires_at);

alter table private.customer_inquiry_rate_limit_events enable row level security;
alter table private.customer_inquiry_submission_fingerprints enable row level security;

revoke all on table private.customer_inquiry_rate_limit_events
from public, anon, authenticated;
revoke all on table private.customer_inquiry_submission_fingerprints
from public, anon, authenticated;

create or replace function public.submit_customer_inquiry_secure(
  p_product_id uuid,
  p_customer_name text,
  p_email text,
  p_phone text,
  p_event_date date,
  p_quantity integer,
  p_message text,
  p_submitter_timezone text,
  p_submitter_utc_offset_minutes integer,
  p_ip_identifier_hash text,
  p_email_identifier_hash text,
  p_submission_fingerprint_hash text,
  p_ip_short_limit integer,
  p_ip_short_window_seconds integer,
  p_ip_long_limit integer,
  p_ip_long_window_seconds integer,
  p_email_limit integer,
  p_email_window_seconds integer,
  p_duplicate_window_seconds integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now timestamptz := now();
  v_duplicate_expires_at timestamptz;
  v_inquiry_id uuid;
  v_retry_after_seconds integer;
  v_window_interval interval;
begin
  if p_ip_identifier_hash is null or btrim(p_ip_identifier_hash) = '' then
    return jsonb_build_object('ok', false, 'error_code', 'invalid_request');
  end if;

  if p_submission_fingerprint_hash is null or btrim(p_submission_fingerprint_hash) = '' then
    return jsonb_build_object('ok', false, 'error_code', 'invalid_request');
  end if;

  if p_email is not null and (p_email_identifier_hash is null or btrim(p_email_identifier_hash) = '') then
    return jsonb_build_object('ok', false, 'error_code', 'invalid_request');
  end if;

  perform pg_advisory_xact_lock(
    hashtext('customer_inquiry_ip'),
    hashtext(p_ip_identifier_hash)
  );

  if p_email_identifier_hash is not null then
    perform pg_advisory_xact_lock(
      hashtext('customer_inquiry_email'),
      hashtext(p_email_identifier_hash)
    );
  end if;

  perform pg_advisory_xact_lock(
    hashtext('customer_inquiry_fingerprint'),
    hashtext(p_submission_fingerprint_hash)
  );

  with deleted_rate_limit_events as (
    delete from private.customer_inquiry_rate_limit_events
    where ctid in (
      select ctid
      from private.customer_inquiry_rate_limit_events
      where expires_at <= v_now
      order by expires_at asc
      limit 500
    )
    returning 1
  ),
  deleted_submission_fingerprints as (
    delete from private.customer_inquiry_submission_fingerprints
    where ctid in (
      select ctid
      from private.customer_inquiry_submission_fingerprints
      where expires_at <= v_now
      order by expires_at asc
      limit 500
    )
    returning 1
  )
  select 1;

  if p_product_id is not null and not exists (
    select 1
    from public.products
    where id = p_product_id
      and active is true
  ) then
    return jsonb_build_object('ok', false, 'error_code', 'invalid_product');
  end if;

  if p_email is null and p_phone is null then
    return jsonb_build_object('ok', false, 'error_code', 'invalid_contact');
  end if;

  select expires_at
  into v_duplicate_expires_at
  from private.customer_inquiry_submission_fingerprints
  where fingerprint_hash = p_submission_fingerprint_hash
    and expires_at > v_now;

  if found then
    return jsonb_build_object(
      'ok', false,
      'error_code', 'duplicate_inquiry',
      'retry_after_seconds',
      greatest(
        1,
        ceil(extract(epoch from (v_duplicate_expires_at - v_now)))::integer
      )
    );
  end if;

  v_window_interval := make_interval(secs => p_ip_short_window_seconds);

  if (
    select count(*)
    from private.customer_inquiry_rate_limit_events
    where scope = 'ip'
      and identifier_hash = p_ip_identifier_hash
      and created_at >= v_now - v_window_interval
  ) >= p_ip_short_limit then
    select greatest(
      1,
      ceil(extract(epoch from ((created_at + v_window_interval) - v_now)))::integer
    )
    into v_retry_after_seconds
    from (
      select created_at
      from private.customer_inquiry_rate_limit_events
      where scope = 'ip'
        and identifier_hash = p_ip_identifier_hash
        and created_at >= v_now - v_window_interval
      order by created_at asc
      limit 1
      offset greatest(p_ip_short_limit - 1, 0)
    ) limited_events;

    return jsonb_build_object(
      'ok', false,
      'error_code', 'rate_limited',
      'retry_after_seconds', coalesce(v_retry_after_seconds, p_ip_short_window_seconds)
    );
  end if;

  v_window_interval := make_interval(secs => p_ip_long_window_seconds);

  if (
    select count(*)
    from private.customer_inquiry_rate_limit_events
    where scope = 'ip'
      and identifier_hash = p_ip_identifier_hash
      and created_at >= v_now - v_window_interval
  ) >= p_ip_long_limit then
    select greatest(
      1,
      ceil(extract(epoch from ((created_at + v_window_interval) - v_now)))::integer
    )
    into v_retry_after_seconds
    from (
      select created_at
      from private.customer_inquiry_rate_limit_events
      where scope = 'ip'
        and identifier_hash = p_ip_identifier_hash
        and created_at >= v_now - v_window_interval
      order by created_at asc
      limit 1
      offset greatest(p_ip_long_limit - 1, 0)
    ) limited_events;

    return jsonb_build_object(
      'ok', false,
      'error_code', 'rate_limited',
      'retry_after_seconds', coalesce(v_retry_after_seconds, p_ip_long_window_seconds)
    );
  end if;

  if p_email_identifier_hash is not null then
    v_window_interval := make_interval(secs => p_email_window_seconds);

    if (
      select count(*)
      from private.customer_inquiry_rate_limit_events
      where scope = 'email'
        and identifier_hash = p_email_identifier_hash
        and created_at >= v_now - v_window_interval
    ) >= p_email_limit then
      select greatest(
        1,
        ceil(extract(epoch from ((created_at + v_window_interval) - v_now)))::integer
      )
      into v_retry_after_seconds
      from (
        select created_at
        from private.customer_inquiry_rate_limit_events
        where scope = 'email'
          and identifier_hash = p_email_identifier_hash
          and created_at >= v_now - v_window_interval
        order by created_at asc
        limit 1
        offset greatest(p_email_limit - 1, 0)
      ) limited_events;

      return jsonb_build_object(
        'ok', false,
        'error_code', 'rate_limited',
        'retry_after_seconds', coalesce(v_retry_after_seconds, p_email_window_seconds)
      );
    end if;
  end if;

  insert into public.customer_inquiries (
    product_id,
    customer_name,
    email,
    phone,
    event_date,
    quantity,
    message,
    submitter_timezone,
    submitter_utc_offset_minutes
  )
  values (
    p_product_id,
    p_customer_name,
    p_email,
    p_phone,
    p_event_date,
    p_quantity,
    p_message,
    p_submitter_timezone,
    p_submitter_utc_offset_minutes
  )
  returning id into v_inquiry_id;

  insert into private.customer_inquiry_rate_limit_events (
    scope,
    identifier_hash,
    expires_at
  )
  values (
    'ip',
    p_ip_identifier_hash,
    v_now + make_interval(secs => p_ip_long_window_seconds)
  );

  if p_email_identifier_hash is not null then
    insert into private.customer_inquiry_rate_limit_events (
      scope,
      identifier_hash,
      expires_at
    )
    values (
      'email',
      p_email_identifier_hash,
      v_now + make_interval(secs => p_email_window_seconds)
    );
  end if;

  insert into private.customer_inquiry_submission_fingerprints (
    fingerprint_hash,
    created_at,
    expires_at
  )
  values (
    p_submission_fingerprint_hash,
    v_now,
    v_now + make_interval(secs => p_duplicate_window_seconds)
  )
  on conflict (fingerprint_hash) do update
  set
    created_at = excluded.created_at,
    expires_at = excluded.expires_at;

  return jsonb_build_object(
    'ok', true,
    'inquiry_id', v_inquiry_id
  );
end;
$$;

revoke all on function public.submit_customer_inquiry_secure(
  uuid,
  text,
  text,
  text,
  date,
  integer,
  text,
  text,
  integer,
  text,
  text,
  text,
  integer,
  integer,
  integer,
  integer,
  integer,
  integer,
  integer
) from public, anon, authenticated;

grant execute on function public.submit_customer_inquiry_secure(
  uuid,
  text,
  text,
  text,
  date,
  integer,
  text,
  text,
  integer,
  text,
  text,
  text,
  integer,
  integer,
  integer,
  integer,
  integer,
  integer,
  integer
) to service_role;

commit;
